export const environment = {
  production: true,
  web:'https://vincicloud.sharepoint.com/sites/SistemadeAdministracionEscolardev',
  relativeweb: '/sites/SistemadeAdministracionEscolardev/',
  menuList:'MenuAdministracionEscolar',
  sexList:'Sexo',
  studentStatusList:'EstatusAlumno',
  schoolStatusList:'EstatusEscolar',
  stageSchoolList:'Division',
  studentList:'Alumnos',
  baseUrl:'https://vincicloud.sharepoint.com',
  cycleList:'CicloEscolar',
  paymentModality:'ModalidadPago',
  paymentConcept:'ConceptosPagos',
  turnList: 'Turno',
  gradeList: 'Grado',
  groupList: 'Grupo',
  documentStudentList:'BibliotecaDocumentosAlumnos',
  monthList:'Meses',
  receivedPersonList:'PersonasAutorizadasCobro',
  paymentWayList:'MetodosPago',
  studentPaymentList:'PagosAlumnos',
  conceptStudentList:'ConceptosDelAlumno',
  scholarshipConfigurationList:'ConfiguracionBeca',
  scholarshipList:'Beca',
  statusScholarshipList:'EstatusBeca',
  countryStatesList: 'Estados'
};
